project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false
website:
  cookie-consent:
    express: true
  reader-mode: true
  site-url: "https://blog.lucascarmo.com.br"
  title: "lucas carmo"
  navbar:
    left:
    - blog.qmd
    - apresentacoes.qmd
    - projetos.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/channel/UC2t8dH8YZhnhDMQFteI0Crw
      - icon: twitter
        href: https://twitter.com/carmo_lcl
      - icon: linkedin
        href: https://linkedin.com/in/lucas-carmo-ba4351b8/
  page-footer:
    border: true
    left: "Copyright 2023, Lucas Carmo" 
    right:
      - icon: github
        href: https://github.com/carmo-lucas
format:
  html:
    theme: 
      light: [flatly, mystyle.scss]
    code-overflow: scroll
    code-copy: hover
    code-fold: true
    code-line-numbers: true
execute:
  freeze: auto
language: _pt-BR-personalizado.yml
smooth-scroll: true
date-format: "YYYY - MM - DD"
