project:
  type: website

website:
  site-url: "hhtps://www.lucascarmo.com.br"
  title: "lucas carmo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/carmo-lucas
      - icon: twitter
        href: https://twitter.com/carmo_lcl
      - icon: linkedin
        href: https://linkedin.com/in/lucas-carmo-ba4351b8/
format:
  html:
    theme: sandstone
    css: styles.css
    code-overflow: scroll
    code-copy: true
    code-fold: true
    code-line-numbers: true

language: _pt-BR-personalizado.yml
smooth-scroll: true
