project:
  type: website

website:
  title: "Attempting Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: lux
    css: styles.css
    code-copy: true
    code-fold: true
    code-line-numbers: true

language: _pt-BR-personalizado.yml
smooth-scroll: true
