---
title: titytuesday 2020 Semana 03
subtitle: Passwords
author: Lucas Carmo
date: 2020-01-14
---

```{r}

library(tidyverse)
library(stringr)
library(janitor)

```

# Data 

```{r}
passwords <-
    readr::read_csv(
        "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv"
    ) %>%
    remove_empty("rows")

```

# Wrangle 

```{r}

pass <- passwords %>%
    mutate(char_category = case_when(
        str_detect(.$password, pattern = "^[a-z]+$") ~ "Only Lowercase",
        str_detect(.$password, pattern = "^[0-9]+$") ~ "Only Numeric",
        str_detect(.$password, pattern = "[:alnum:]") ~ "Alphanumeric",
        str_detect(.$password, pattern = "[:punct:]") ~ "With Punctuation",
    )) %>%
    select(password, char_category, strength)

```

# Plot 

```{r}

ggplot(pass, aes(
    x = char_category,
    y = strength,
    color = char_category
)) +
    geom_violin(fill = NA) +
    geom_jitter(width = 0.1, alpha = 0.3, size = 0.8) +
    theme(
        panel.background = element_rect(fill = "#132124", color = NULL),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        legend.position = "none",
        text = element_text(family = "Fira Code", color = "white"),
        axis.text = element_text(color = "white"),
        plot.title = element_text(lineheight = 1),
        plot.background = element_rect(fill = "#132125", color = NULL),
        plot.caption = element_text(hjust = 0)
    ) +
    scale_color_manual(values = c("#d33682", "#268bd2", "#2aa198")) +
    coord_flip() +
    labs(
        y = "\nStrength",
        x = "",
        title = "Top 500 passwords do not \nfollow security recommendations",
        caption = "\nData: Information is beautiful | Viz: @carmo_lcl"
    ) +
    annotate(
        geom = "text", x = 2, y = 20,
        label = 
        "Passwords containing only letters \n
        or words are not as strong and more \n
        frequent than passwords containing \n
        a combination of these elements",
        family = "Courier", color = "white", hjust = "left", size = 3
    )


```