---
author: Lucas Carmo
title: tidytuesday 2020 Semana 02
subtitle: Australian Fires
date: 2020-01-07
---

```{r}

library(tidyverse)
library(here)
library(lubridate)

```
# Data 

```{r}
temperature <-
    readr::read_csv(
        "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv"
    )

```

# Wrangle 

```{r}

city_temp <- temperature %>%
    filter(
        city_name %in% c("MELBOURNE", "PERTH", "SYDNEY", "BRISBANE"),
        date >= as_date("1970-01-01"),
        date < as_date("2019-01-01")
    ) %>%
    group_by(city_name,
        year = year(date),
        month = month(date, label = TRUE)
    ) %>%
    summarise(temp = mean(temperature, na.rm = TRUE))

```

# Plot 


```{r}
#| fig-column: screen-inset

ggplot(city_temp, aes(
    x = year,
    y = forcats::fct_rev(month),
    fill = temp
    )
) +
    geom_raster() +
    scale_fill_viridis_c(option = "inferno") +
    theme_minimal() +
    theme(
        text = element_text(family = "Fira Sans"),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0)
    ) +
    facet_wrap(~city_name) +
    labs(
        title = "Australian Cities Temperature Over Time",
        subtitle = "Melbourne has lower mean temperatures in comparison",
        y = "",
        x = "",
        fill = "Average \ntemperature \n(°C)",
        caption =
            "Data: Australian Bureau of Meteorology\nVis: Lucas C. L. do Carmo"
    )

```

